theme =  "dracula_at_night"

[editor]
bufferline = "multiple"
auto-completion = true
auto-format = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "position-percentage", "file-encoding"]
mode.normal = "â‚ <Normal>"
mode.insert = "â¸™ <Insert>"
mode.select = "ğ«° <Select>"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "â¸½" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
skip-levels = 1
